const x  = 20
try {
    x = 2
} catch (error) {
    
    console.log(`Erro : ${error}`)
}